<?php

use App\Http\Controllers\Api\V1\AccountingSettingsController;
use App\Http\Controllers\Api\V1\AuthenticationController;
use App\Http\Controllers\Api\V1\CompanyProfileController;
use App\Http\Controllers\Api\V1\CoreErpController;
use App\Http\Controllers\Api\V1\LocalLicenseController;
use App\Http\Controllers\Api\V1\OperationsController;
use App\Http\Controllers\Web\CompanyAccessController;
use App\Services\SubscriptionLifecycle;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

Route::prefix('v1')->group(function (): void {
    Route::get('/health', fn () => response()->json(['status' => 'ok', 'version' => 'v1']))->name('api.v1.health');
    Route::get('/version', fn () => response()->json(['data' => ['api' => 'v1', 'application' => config('app.name'), 'laravel' => app()->version()]]))->name('api.v1.version');
    Route::post('/login', [AuthenticationController::class, 'login'])->middleware('throttle:login')->name('api.v1.login');
    Route::post('/license/activate', [LocalLicenseController::class, 'activate'])->middleware('throttle:5,1')->name('api.v1.license.activate');
    Route::middleware(['auth:sanctum', 'account.type:company', 'tenant', 'subscription', 'local.license'])->group(function (): void {
        Route::get('/subscription', function (Request $request, SubscriptionLifecycle $lifecycle) {
            $subscription = $lifecycle->currentFor($request->attributes->get('company'));

            return response()->json([
                'status' => $request->attributes->get('subscription_status'),
                'plan' => $subscription?->plan?->only(['id', 'name', 'duration']),
                'ends_at' => $subscription?->ends_at,
            ]);
        })->middleware('throttle:api.read')->name('api.v1.subscription');
        Route::post('/subscription/contact', fn () => response()->json(['status' => 'contact_requested']))->middleware('throttle:api.write')->name('api.v1.subscription.contact');
        Route::post('/subscription/renew', fn () => response()->json(['status' => 'renewal_requested']))->middleware('throttle:api.write')->name('api.v1.subscription.renew');
        Route::put('/password', [CompanyProfileController::class, 'updatePassword'])->middleware('throttle:api.write')->name('api.v1.password.update');
        Route::put('/profile', [CompanyProfileController::class, 'update'])->middleware('throttle:api.write')->name('api.v1.profile.update');
        Route::get('/accounting-settings', [AccountingSettingsController::class, 'show'])->middleware('throttle:api.read')->name('api.v1.accounting-settings.show');
        Route::put('/accounting-settings', [AccountingSettingsController::class, 'update'])->middleware('throttle:api.write')->name('api.v1.accounting-settings.update');
        Route::post('/logout', [AuthenticationController::class, 'logout'])->middleware('throttle:api.write')->name('api.v1.logout');
        Route::get('/me', [CoreErpController::class, 'me'])->middleware('throttle:api.read')->name('api.v1.me');
        Route::get('/dashboard', [CoreErpController::class, 'dashboard'])->middleware('can:dashboard.view')->middleware('throttle:api.read')->name('api.v1.dashboard');
        Route::middleware('can:branches.view')->group(function (): void {
            Route::get('/branches', [CoreErpController::class, 'branches'])->middleware('throttle:api.read')->name('api.v1.branches.index');
            Route::get('/warehouses', [CoreErpController::class, 'warehouses'])->middleware('throttle:api.read')->name('api.v1.warehouses.index');
        });
        Route::middleware('can:branches.create')->post('/branches', [CoreErpController::class, 'createBranch'])->middleware('throttle:api.write')->name('api.v1.branches.store');
        Route::middleware('can:branches.update')->put('/branches/{branch}', [CoreErpController::class, 'updateBranch'])->middleware('throttle:api.write')->name('api.v1.branches.update');
        Route::middleware('can:branches.archive')->post('/branches/{branch}/archive', [CoreErpController::class, 'archiveBranch'])->middleware('throttle:api.write')->name('api.v1.branches.archive');
        Route::middleware('can:warehouses.update')->put('/warehouses/{warehouse}', [CoreErpController::class, 'updateWarehouse'])->middleware('throttle:api.write')->name('api.v1.warehouses.update');
        Route::middleware('can:warehouses.archive')->post('/warehouses/{warehouse}/archive', [CoreErpController::class, 'archiveWarehouse'])->middleware('throttle:api.write')->name('api.v1.warehouses.archive');
        Route::middleware('can:products.view')->get('/product-types', [CoreErpController::class, 'productTypes'])->middleware('throttle:api.read');
        Route::middleware('can:products.create')->post('/product-types', [CoreErpController::class, 'createProductType'])->middleware('throttle:api.write');
        Route::middleware('can:products.update')->put('/product-types/{productType}', [CoreErpController::class, 'updateProductType'])->middleware('throttle:api.write');
        Route::middleware('can:products.view')->get('/diameters', [CoreErpController::class, 'diameters'])->middleware('throttle:api.read');
        Route::middleware('can:products.create')->post('/diameters', [CoreErpController::class, 'createDiameter'])->middleware('throttle:api.write');
        Route::middleware('can:products.update')->put('/diameters/{diameter}', [CoreErpController::class, 'updateDiameter'])->middleware('throttle:api.write');
        Route::middleware('can:products.view')->get('/products', [CoreErpController::class, 'products'])->middleware('throttle:api.read');
        Route::middleware('can:products.create')->post('/products', [CoreErpController::class, 'createProduct'])->middleware('throttle:api.write');
        Route::middleware('can:products.create')->post('/inventory/type-diameter-profile', [CoreErpController::class, 'saveTypeDiameterProfile'])->middleware('throttle:api.write');
        Route::middleware('can:products.update')->put('/products/{product}', [CoreErpController::class, 'updateProduct'])->middleware('throttle:api.write');
        Route::middleware('can:products.archive')->post('/products/{product}/archive', [CoreErpController::class, 'archiveProduct'])->middleware('throttle:api.write');
        Route::middleware('can:inventory.view')->get('/inventory/matrix', [CoreErpController::class, 'inventoryMatrix'])->middleware('throttle:api.read');
        Route::middleware('can:inventory.transfer')->get('/inventory/transfers', [CoreErpController::class, 'transfers'])->middleware('throttle:api.read');
        Route::middleware('can:inventory.transfer')->post('/inventory/transfers', [CoreErpController::class, 'createTransfer'])->middleware('throttle:api.write');
        Route::middleware('can:parties.view')->get('/parties', [CoreErpController::class, 'parties'])->middleware('throttle:api.read');
        Route::middleware('can:parties.create')->post('/parties', [CoreErpController::class, 'createParty'])->middleware('throttle:api.write');
        Route::middleware('can:parties.update')->put('/parties/{party}', [CoreErpController::class, 'updateParty'])->middleware('throttle:api.write');
        Route::middleware('can:accounting.view')->get('/accounts', [CoreErpController::class, 'accounts'])->middleware('throttle:api.read');
        Route::middleware('can:accounting.view')->get('/accounts/{account}/statement', [CoreErpController::class, 'accountStatement'])->middleware('throttle:api.read');
        Route::middleware('can:accounting.create')->post('/accounts', [CoreErpController::class, 'createAccount'])->middleware('throttle:api.write');
        Route::middleware('can:accounting.create')->put('/accounts/{account}', [CoreErpController::class, 'updateAccount'])->middleware('throttle:api.write');
        Route::middleware('can:accounting.view')->get('/cashboxes', [CoreErpController::class, 'cashboxes'])->middleware('throttle:api.read');
        Route::middleware('can:accounting.create')->post('/cashboxes', [CoreErpController::class, 'createCashbox'])->middleware('throttle:api.write');
        Route::middleware('can:accounting.view')->get('/banks', [CoreErpController::class, 'banks'])->middleware('throttle:api.read');
        Route::middleware('can:accounting.create')->post('/banks', [CoreErpController::class, 'createBank'])->middleware('throttle:api.write');
        Route::middleware('can:accounting.view')->get('/fiscal-periods', [CoreErpController::class, 'periods'])->middleware('throttle:api.read');
        Route::middleware('can:accounting.create')->post('/fiscal-periods', [CoreErpController::class, 'createPeriod'])->middleware('throttle:api.write');
        Route::middleware('can:accounting.close_period')->post('/fiscal-periods/{period}/close', [CoreErpController::class, 'closePeriod'])->middleware('throttle:api.write');
        Route::middleware('can:accounting.view')->get('/receipts', [CoreErpController::class, 'receipts'])->middleware('throttle:api.read');
        Route::middleware('can:accounting.post')->post('/receipts', [CoreErpController::class, 'createReceipt'])->middleware('throttle:api.write');
        Route::middleware('can:accounting.view')->get('/payment-vouchers', [CoreErpController::class, 'vouchers'])->middleware('throttle:api.read');
        Route::middleware('can:accounting.post')->post('/payment-vouchers', [CoreErpController::class, 'createVoucher'])->middleware('throttle:api.write');
        Route::middleware('can:accounting.view')->get('/journals', [CoreErpController::class, 'report'])->defaults('report', 'journal')->middleware('throttle:api.read');
        Route::middleware('can:accounting.view')->get('/reports/{report}', [CoreErpController::class, 'report'])->whereIn('report', ['account-statement', 'ledger', 'trial-balance', 'income-statement', 'balance-sheet', 'debtors', 'receivables', 'payables', 'creditors'])->middleware('throttle:api.reports');
        Route::middleware('can:accounting.reverse')->post('/journals/{entry}/reverse', [CoreErpController::class, 'reverseJournal'])->middleware('throttle:api.write');
        Route::middleware('can:purchases.view')->get('/purchase-bills', [OperationsController::class, 'purchases'])->middleware('throttle:api.read');
        Route::middleware('can:purchases.create')->post('/purchase-bills', [OperationsController::class, 'storePurchase'])->middleware('throttle:api.write');
        Route::middleware('can:purchases.create')->get('/purchase-bills/near-duplicates', [OperationsController::class, 'purchaseWarnings'])->middleware('throttle:api.read');
        Route::middleware('can:purchases.view')->get('/purchase-bills/{purchaseBill}', [OperationsController::class, 'purchase'])->middleware('throttle:api.read');
        Route::middleware('can:purchases.update')->put('/purchase-bills/{purchaseBill}', [OperationsController::class, 'updatePurchase'])->middleware('throttle:api.write');
        Route::middleware('can:purchases.view')->get('/bills/{type}/{bill}/transport-allocation', [OperationsController::class, 'allocation'])->middleware('throttle:api.read');
        Route::middleware('can:purchases.approve')->post('/purchase-bills/{purchaseBill}/approve', [OperationsController::class, 'approvePurchase'])->middleware('throttle:api.write');
        Route::middleware('can:purchases.reverse')->post('/purchase-bills/{purchaseBill}/reverse', [OperationsController::class, 'reversePurchase'])->middleware('throttle:api.write');
        Route::middleware('can:purchases.update_approved')->put('/purchase-bills/{purchaseBill}/revision', [OperationsController::class, 'revisePurchase'])->middleware('throttle:api.write');
        Route::middleware('can:sales.view')->get('/sales-bills', [OperationsController::class, 'sales'])->middleware('throttle:api.read');
        Route::middleware('can:sales.create')->post('/sales-bills', [OperationsController::class, 'storeSales'])->middleware('throttle:api.write');
        Route::middleware('can:sales.create')->get('/sales-bills/near-duplicates', [OperationsController::class, 'salesWarnings'])->middleware('throttle:api.read');
        Route::middleware('can:sales.view')->get('/sales-bills/{salesBill}', [OperationsController::class, 'salesBill'])->middleware('throttle:api.read');
        Route::middleware('can:sales.update')->put('/sales-bills/{salesBill}', [OperationsController::class, 'updateSales'])->middleware('throttle:api.write');
        Route::middleware('can:sales.approve')->post('/sales-bills/{salesBill}/approve', [OperationsController::class, 'approveSales'])->middleware('throttle:api.write');
        Route::middleware('can:sales.reverse')->post('/sales-bills/{salesBill}/reverse', [OperationsController::class, 'reverseSales'])->middleware('throttle:api.write');
        Route::middleware('can:sales.update_approved')->put('/sales-bills/{salesBill}/revision', [OperationsController::class, 'reviseSales'])->middleware('throttle:api.write');
        Route::middleware('can:fleet.view')->get('/fleet/vehicles', [OperationsController::class, 'vehicles'])->middleware('throttle:api.read');
        Route::middleware('can:fleet.create')->post('/fleet/vehicles', [OperationsController::class, 'storeVehicle'])->middleware('throttle:api.write');
        Route::middleware('can:fleet.update')->put('/fleet/vehicles/{vehicle}', [OperationsController::class, 'updateVehicle'])->middleware('throttle:api.write');
        Route::middleware('can:fleet.view')->get('/fleet/drivers', [OperationsController::class, 'drivers'])->middleware('throttle:api.read');
        Route::middleware('can:fleet.create')->post('/fleet/drivers', [OperationsController::class, 'storeDriver'])->middleware('throttle:api.write');
        Route::middleware('can:fleet.update')->put('/fleet/drivers/{driver}', [OperationsController::class, 'updateDriver'])->middleware('throttle:api.write');
        Route::middleware('can:fleet.view')->get('/fleet/trips', [OperationsController::class, 'trips'])->middleware('throttle:api.read');
        Route::middleware('can:fleet.create')->post('/fleet/trips', [OperationsController::class, 'storeTrip'])->middleware('throttle:api.write');
        Route::middleware('can:fleet.update')->put('/fleet/trips/{trip}', [OperationsController::class, 'updateTrip'])->middleware('throttle:api.write');
        Route::middleware('can:fleet.approve')->post('/fleet/trips/{trip}/approve', [OperationsController::class, 'approveTrip'])->middleware('throttle:api.write');
        Route::middleware('can:fleet.approve')->post('/fleet/trips/{trip}/reverse', [OperationsController::class, 'reverseTrip'])->middleware('throttle:api.write');
        Route::middleware('can:fleet.approve')->post('/fleet/trips/{trip}/cancel', [OperationsController::class, 'cancelTrip'])->middleware('throttle:api.write');
        Route::middleware('can:fleet.expenses')->get('/fleet/expenses', [OperationsController::class, 'expenses'])->middleware('throttle:api.read');
        Route::middleware('can:fleet.expenses')->post('/fleet/expenses', [OperationsController::class, 'storeExpense'])->middleware('throttle:api.write');
        Route::middleware('can:fleet.expenses')->put('/fleet/expenses/{expense}', [OperationsController::class, 'updateExpense'])->middleware('throttle:api.write');
        Route::middleware('can:fleet.approve')->post('/fleet/expenses/{expense}/reverse', [OperationsController::class, 'reverseExpense'])->middleware('throttle:api.write');
        Route::middleware('can:fleet.approve')->post('/fleet/expenses/{expense}/approve', [OperationsController::class, 'approveExpense'])->middleware('throttle:api.write');
        Route::middleware('can:fleet.maintenance')->get('/fleet/maintenance', [OperationsController::class, 'maintenance'])->middleware('throttle:api.read');
        Route::middleware('can:fleet.maintenance')->post('/fleet/maintenance', [OperationsController::class, 'storeMaintenance'])->middleware('throttle:api.write');
        Route::middleware('can:fleet.maintenance')->put('/fleet/maintenance/{record}', [OperationsController::class, 'updateMaintenance'])->middleware('throttle:api.write');
        Route::middleware('can:fleet.approve')->post('/fleet/maintenance/{record}/reverse', [OperationsController::class, 'reverseMaintenance'])->middleware('throttle:api.write');
        Route::middleware('can:fleet.approve')->post('/fleet/maintenance/{record}/approve', [OperationsController::class, 'approveMaintenance'])->middleware('throttle:api.write');
        Route::middleware('can:fleet.view')->get('/fleet/reports/{report}', [OperationsController::class, 'report'])->whereIn('report', ['vehicle-pl', 'trip-cost', 'fuel', 'driver-performance', 'expenses-by-category', 'maintenance-period', 'inactive-vehicles', 'branch-performance'])->middleware('throttle:api.reports');
        Route::middleware('can:roles.view')->get('/roles', [CompanyAccessController::class, 'roles'])->middleware('throttle:api.read');
        Route::middleware('can:roles.create')->post('/roles', [CompanyAccessController::class, 'storeRole'])->middleware('throttle:api.write');
        Route::middleware('can:roles.assign_permissions')->put('/roles/{role}', [CompanyAccessController::class, 'updateRole'])->middleware('throttle:api.write');
        Route::middleware('can:users.view')->get('/users', [CompanyAccessController::class, 'users'])->middleware('throttle:api.read');
        Route::middleware('can:users.create')->post('/users', [CompanyAccessController::class, 'storeUser'])->middleware('throttle:api.write');
        Route::middleware('can:users.update')->put('/users/{user}', [CompanyAccessController::class, 'updateUser'])->middleware('throttle:api.write');
        Route::middleware('can:users.view_activity')->get('/users/{user}/activity', [CompanyAccessController::class, 'activity'])->middleware('throttle:api.read');
        Route::middleware('can:users.update')->put('/users/{user}/permissions', [CompanyAccessController::class, 'setDirectPermissions'])->middleware('throttle:api.write');
        Route::middleware('can:users.deactivate')->patch('/users/{user}/status', [CompanyAccessController::class, 'setStatus'])->middleware('throttle:api.write');
        Route::middleware('can:users.reset_password')->put('/users/{user}/password', [CompanyAccessController::class, 'resetPassword'])->middleware('throttle:api.write');
    });
});
