import { useState } from 'react';
import { Link, usePage } from '@inertiajs/react';
import CompanyLayout from '../../Layouts/CompanyLayout';
import { translate } from '../../i18n';
import { useCoreApi } from '../../useCoreApi';

export default function Accounting({ accounts, cashboxes, banks, periods, parties, receipts, vouchers, capabilities = {} }) {
    const page = usePage();
    const { locale } = page.props;
    const { url } = page;
    const t = (key) => translate(locale, key);
    const { notice, processing, send } = useCoreApi();
    const query = new URLSearchParams(url?.split('?')[1] ?? '');
    const linkedPartyType = query.get('counterparty_type');
    const linkedPartyId = query.get('party_id') ?? '';
    const [cashboxName, setCashboxName] = useState('');
    const [bankName, setBankName] = useState('');
    const [bankNumber, setBankNumber] = useState('');
    const [childAccount, setChildAccount] = useState({ parent_id: '', name: '' });
    const [editingAccount, setEditingAccount] = useState(null);
    const calendarYear = new Date().getFullYear();
    const [period, setPeriod] = useState({ name: String(calendarYear), starts_on: `${calendarYear}-01-01`, ends_on: `${calendarYear}-12-31` });
    const [receipt, setReceipt] = useState({ counterparty_type: 'customer', party_id: linkedPartyType === 'customer' ? linkedPartyId : '', other_account_id: '', cashbox_id: '', bank_id: '', receipt_date: new Date().toISOString().slice(0, 10), amount: '', delivered_by: '', received_by: '', location: '', notes: '' });
    const [voucher, setVoucher] = useState({ counterparty_type: 'supplier', party_id: linkedPartyType === 'supplier' ? linkedPartyId : '', other_account_id: '', cashbox_id: '', bank_id: '', voucher_date: new Date().toISOString().slice(0, 10), amount: '', paid_by: '', received_by: '', location: '', notes: '' });

    const reports = [
        ['journal', 'journal'], ['ledger', 'ledger'], ['trial-balance', 'trialBalance'], ['income-statement', 'incomeStatement'],
        ['balance-sheet', 'balanceSheet'], ['debtors', 'debtors'],
    ];
    const receiptCashAccountId = cashboxes.find((item) => String(item.id) === String(receipt.cashbox_id))?.account_id ?? banks.find((item) => String(item.id) === String(receipt.bank_id))?.account_id;
    const voucherCashAccountId = cashboxes.find((item) => String(item.id) === String(voucher.cashbox_id))?.account_id ?? banks.find((item) => String(item.id) === String(voucher.bank_id))?.account_id;
    const postingAccounts = (cashAccountId) => accounts.filter((account) => account.is_active !== false && !accounts.some((child) => Number(child.parent_id) === Number(account.id)) && Number(account.id) !== Number(cashAccountId));

    return <CompanyLayout title={t('accounting')}>
        <h1 className="text-2xl font-semibold">{t('accounting')}</h1>
        {notice.message && <p role="status" className={`mt-4 border-l-4 bg-white p-3 text-sm ${notice.type === 'error' ? 'border-red-700' : 'border-[#34795c]'}`}>{notice.message}</p>}
        <section className="mt-4 border-y border-[#d7ddd5] py-4"><h2 className="font-semibold">{t('reports')}</h2><div className="mt-3 flex flex-wrap gap-2">{reports.map(([slug, label]) => <Link key={slug} href={`/reports/${slug}`} className="border border-[#34795c] px-3 py-2 text-sm">{t(label)}</Link>)}</div></section>
        <section className="mt-7"><h2 className="font-semibold">{t('chart')}</h2><div className="mt-3 divide-y divide-[#d7ddd5] border-y border-[#d7ddd5]">{accounts.map((account) => <div key={account.id} className="flex justify-between gap-4 py-2 text-sm"><Link href={`/reports/account-statement?account_id=${account.id}`} className="underline">{account.code} · {account.name}</Link><span className="flex items-center gap-3 text-xs text-[#637067]">{account.account_type}{capabilities['accounting.create'] && <button onClick={() => setEditingAccount({ id: account.id, name: account.name, parent_id: account.parent_id ?? '' })} className="underline">{t('edit')}</button>}</span></div>)}</div>{capabilities['accounting.create'] && <form onSubmit={(event) => { event.preventDefault(); send('accounts', 'POST', childAccount); }} className="mt-4 flex flex-wrap gap-2"><select required aria-label={t('parentAccount')} value={childAccount.parent_id} onChange={(event) => setChildAccount({ ...childAccount, parent_id: event.target.value })} className="min-w-48 border border-[#c9d0c8] bg-white px-3 py-2"><option value="">{t('parentAccount')}</option>{accounts.map((account) => <option key={account.id} value={account.id}>{account.code} · {account.name}</option>)}</select><input required aria-label={t('accountName')} placeholder={t('accountName')} value={childAccount.name} onChange={(event) => setChildAccount({ ...childAccount, name: event.target.value })} className="min-w-48 flex-1 border border-[#c9d0c8] bg-white px-3 py-2" /><button className="border border-[#34795c] px-4 py-2">{t('create')}</button></form>}{editingAccount && <form onSubmit={(event) => { event.preventDefault(); send(`accounts/${editingAccount.id}`, 'PUT', editingAccount); }} className="mt-4 flex flex-wrap gap-2"><input required aria-label={t('accountName')} value={editingAccount.name} onChange={(event) => setEditingAccount({ ...editingAccount, name: event.target.value })} className="min-w-48 border px-3 py-2" /><input list="account-parent-options" aria-label={t('parentAccount')} placeholder={t('parentAccount')} value={editingAccount.parent_id} onChange={(event) => setEditingAccount({ ...editingAccount, parent_id: event.target.value })} className="min-w-48 border px-3 py-2" /><datalist id="account-parent-options">{accounts.filter((account) => account.id !== editingAccount.id).map((account) => <option key={account.id} value={account.id}>{account.code} · {account.name}</option>)}</datalist><button className="border border-[#34795c] px-4 py-2">{t('saveChanges')}</button></form>}</section>
        <section className="mt-8 grid gap-6 border-t border-[#d7ddd5] pt-5 lg:grid-cols-2"><div><h2 className="font-semibold">{t('cashboxes')}</h2><div className="mt-2 text-sm">{cashboxes.map((cashbox) => <p key={cashbox.id} className="py-1">{cashbox.name} · {cashbox.account?.code}</p>)}</div>{capabilities['accounting.create'] && <form onSubmit={(event) => { event.preventDefault(); send('cashboxes', 'POST', { name: cashboxName }); }} className="mt-3 flex gap-2"><input required aria-label={t('cashboxes')} value={cashboxName} onChange={(event) => setCashboxName(event.target.value)} placeholder={t('cashboxes')} className="min-w-0 flex-1 border border-[#c9d0c8] bg-white px-3 py-2" /><button className="border border-[#34795c] px-3 py-2">{t('createCashbox')}</button></form>}</div>
            <div><h2 className="font-semibold">{t('banks')}</h2><div className="mt-2 text-sm">{banks.map((bank) => <p key={bank.id} className="py-1">{bank.name} · {bank.account?.code}</p>)}</div>{capabilities['accounting.create'] && <form onSubmit={(event) => { event.preventDefault(); send('banks', 'POST', { name: bankName, account_number: bankNumber || null }); }} className="mt-3 flex flex-wrap gap-2"><input required aria-label={t('banks')} value={bankName} onChange={(event) => setBankName(event.target.value)} placeholder={t('banks')} className="min-w-32 flex-1 border border-[#c9d0c8] bg-white px-3 py-2" /><input aria-label="Account number" value={bankNumber} onChange={(event) => setBankNumber(event.target.value)} placeholder="Account number" className="min-w-32 flex-1 border border-[#c9d0c8] bg-white px-3 py-2" /><button className="border border-[#34795c] px-3 py-2">{t('createBank')}</button></form>}</div></section>
        <section className="mt-8 border-t border-[#d7ddd5] pt-5"><h2 className="font-semibold">{t('fiscalPeriods')}</h2><div className="mt-3 divide-y divide-[#d7ddd5] border-y border-[#d7ddd5]">{periods.map((periodItem) => <div key={periodItem.id} className="flex flex-wrap items-center justify-between gap-3 py-3 text-sm"><span>{periodItem.name} · {periodItem.starts_on} — {periodItem.ends_on} · {periodItem.status}</span>{periodItem.status === 'open' && capabilities['accounting.close_period'] && <button onClick={() => window.confirm(`${t('closePeriod')} ${periodItem.name}?`) && send(`fiscal-periods/${periodItem.id}/close`, 'POST')} className="underline">{t('closePeriod')}</button>}</div>)}</div>{capabilities['accounting.create'] && <form onSubmit={(event) => { event.preventDefault(); send('fiscal-periods', 'POST', period); }} className="mt-4 grid gap-2 sm:grid-cols-4"><input required aria-label={t('periodName')} value={period.name} onChange={(event) => setPeriod({ ...period, name: event.target.value })} className="border border-[#c9d0c8] px-3 py-2" /><input required type="date" aria-label={t('periodStart')} value={period.starts_on} onChange={(event) => setPeriod({ ...period, starts_on: event.target.value })} className="border border-[#c9d0c8] px-3 py-2" /><input required type="date" aria-label={t('periodEnd')} value={period.ends_on} onChange={(event) => setPeriod({ ...period, ends_on: event.target.value })} className="border border-[#c9d0c8] px-3 py-2" /><button className="border border-[#34795c] px-3 py-2">{t('createPeriod')}</button></form>}</section>
        <section className="mt-8 grid gap-8 border-t border-[#d7ddd5] pt-5 lg:grid-cols-2"><div><h2 className="font-semibold">{t('receipts')}</h2><div className="mt-3 divide-y divide-[#d7ddd5] border-y border-[#d7ddd5]">{receipts.map((item) => <p id={`receipt-${item.id}`} key={item.id} className="py-2 text-sm">{item.receipt_number} · {item.receipt_date} · {item.amount} EGP · {item.status === 'posted' ? t('posted') : item.status}</p>)}{receipts.length === 0 && <p className="py-3 text-sm text-[#637067]">{t('noRecords')}</p>}</div></div><div><h2 className="font-semibold">{t('vouchers')}</h2><div className="mt-3 divide-y divide-[#d7ddd5] border-y border-[#d7ddd5]">{vouchers.map((item) => <p id={`voucher-${item.id}`} key={item.id} className="py-2 text-sm">{item.voucher_number} · {item.voucher_date} · {item.amount} EGP · {item.status === 'posted' ? t('posted') : item.status}</p>)}{vouchers.length === 0 && <p className="py-3 text-sm text-[#637067]">{t('noRecords')}</p>}</div></div></section>
        <section className="mt-8 border-t border-[#d7ddd5] pt-5"><h2 className="font-semibold">{t('reports')}</h2><div className="mt-3 flex flex-wrap gap-2">{reports.map(([slug, label]) => <Link key={slug} href={`/reports/${slug}`} className="border border-[#34795c] px-3 py-2 text-sm">{t(label)}</Link>)}</div></section>
        <div className="mt-8 grid gap-8 xl:grid-cols-2">
            {capabilities['accounting.post'] && <section className="border-t border-[#d7ddd5] pt-5"><h2 className="font-semibold">{t('receipts')}</h2><form onSubmit={(event) => { event.preventDefault(); send('receipts', 'POST', receipt); }} className="mt-4 grid gap-3 sm:grid-cols-2">
                <select aria-label={t('counterpartyType')} value={receipt.counterparty_type} onChange={(event) => setReceipt({ ...receipt, counterparty_type: event.target.value, party_id: '', other_account_id: '' })} className="border border-[#c9d0c8] bg-white px-3 py-2"><option value="customer">{t('isCustomer')}</option><option value="other">{t('otherAccount')}</option></select>
                {receipt.counterparty_type === 'customer' ? <select required aria-label={t('customer')} value={receipt.party_id} onChange={(event) => setReceipt({ ...receipt, party_id: event.target.value })} className="border border-[#c9d0c8] bg-white px-3 py-2"><option value="">{t('customer')}</option>{parties.filter((party) => party.is_customer).map((party) => <option key={party.id} value={party.id}>{party.name}</option>)}</select> : <select required aria-label={t('accountName')} value={receipt.other_account_id} onChange={(event) => setReceipt({ ...receipt, other_account_id: event.target.value })} className="border border-[#c9d0c8] bg-white px-3 py-2"><option value="">{t('accountName')}</option>{postingAccounts(receiptCashAccountId).map((account) => <option key={account.id} value={account.id}>{account.code} · {account.name}</option>)}</select>}
                <input required type="date" aria-label={t('entryDate')} value={receipt.receipt_date} onChange={(event) => setReceipt({ ...receipt, receipt_date: event.target.value })} className="border border-[#c9d0c8] bg-white px-3 py-2" />
                <input required type="number" min="0.01" step="0.01" aria-label={t('amount')} placeholder={t('amount')} value={receipt.amount} onChange={(event) => setReceipt({ ...receipt, amount: event.target.value })} className="border border-[#c9d0c8] bg-white px-3 py-2" />
                <select aria-label={t('cashboxes')} value={receipt.cashbox_id} onChange={(event) => setReceipt({ ...receipt, cashbox_id: event.target.value, bank_id: '' })} className="border border-[#c9d0c8] bg-white px-3 py-2"><option value="">{t('cashboxes')}</option>{cashboxes.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select>
                <select aria-label={t('banks')} value={receipt.bank_id} onChange={(event) => setReceipt({ ...receipt, bank_id: event.target.value, cashbox_id: '' })} className="border border-[#c9d0c8] bg-white px-3 py-2"><option value="">{t('banks')}</option>{banks.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select>
                <input aria-label={t('notes')} placeholder={t('notes')} value={receipt.notes} onChange={(event) => setReceipt({ ...receipt, notes: event.target.value })} className="border border-[#c9d0c8] bg-white px-3 py-2" />
                <button disabled={processing} className="bg-[#34795c] px-4 py-2 text-white sm:col-span-2">{t('postReceipt')}</button>
            </form></section>}
            {capabilities['accounting.post'] && <section className="border-t border-[#d7ddd5] pt-5"><h2 className="font-semibold">{t('vouchers')}</h2><form onSubmit={(event) => { event.preventDefault(); send('payment-vouchers', 'POST', voucher); }} className="mt-4 grid gap-3 sm:grid-cols-2">
                <select aria-label={t('counterpartyType')} value={voucher.counterparty_type} onChange={(event) => setVoucher({ ...voucher, counterparty_type: event.target.value, party_id: '', other_account_id: '' })} className="border border-[#c9d0c8] bg-white px-3 py-2"><option value="supplier">{t('isSupplier')}</option><option value="other">{t('otherAccount')}</option></select>
                {voucher.counterparty_type === 'supplier' ? <select required aria-label={t('supplier')} value={voucher.party_id} onChange={(event) => setVoucher({ ...voucher, party_id: event.target.value })} className="border border-[#c9d0c8] bg-white px-3 py-2"><option value="">{t('supplier')}</option>{parties.filter((party) => party.is_supplier).map((party) => <option key={party.id} value={party.id}>{party.name}</option>)}</select> : <select required aria-label={t('accountName')} value={voucher.other_account_id} onChange={(event) => setVoucher({ ...voucher, other_account_id: event.target.value })} className="border border-[#c9d0c8] bg-white px-3 py-2"><option value="">{t('accountName')}</option>{postingAccounts(voucherCashAccountId).map((account) => <option key={account.id} value={account.id}>{account.code} · {account.name}</option>)}</select>}
                <input required type="date" aria-label={t('entryDate')} value={voucher.voucher_date} onChange={(event) => setVoucher({ ...voucher, voucher_date: event.target.value })} className="border border-[#c9d0c8] bg-white px-3 py-2" />
                <input required type="number" min="0.01" step="0.01" aria-label={t('amount')} placeholder={t('amount')} value={voucher.amount} onChange={(event) => setVoucher({ ...voucher, amount: event.target.value })} className="border border-[#c9d0c8] bg-white px-3 py-2" />
                <select aria-label={t('cashboxes')} value={voucher.cashbox_id} onChange={(event) => setVoucher({ ...voucher, cashbox_id: event.target.value, bank_id: '' })} className="border border-[#c9d0c8] bg-white px-3 py-2"><option value="">{t('cashboxes')}</option>{cashboxes.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select>
                <select aria-label={t('banks')} value={voucher.bank_id} onChange={(event) => setVoucher({ ...voucher, bank_id: event.target.value, cashbox_id: '' })} className="border border-[#c9d0c8] bg-white px-3 py-2"><option value="">{t('banks')}</option>{banks.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select>
                <input aria-label={t('notes')} placeholder={t('notes')} value={voucher.notes} onChange={(event) => setVoucher({ ...voucher, notes: event.target.value })} className="border border-[#c9d0c8] bg-white px-3 py-2" />
                <button disabled={processing} className="bg-[#a64b36] px-4 py-2 text-white sm:col-span-2">{t('postVoucher')}</button>
            </form></section>}
        </div>
    </CompanyLayout>;
}
