import CompanyLayout from '../../Layouts/CompanyLayout';
import { Link, usePage } from '@inertiajs/react';
import { translate } from '../../i18n';

function Stat({ label, value, unit, tone, href }) { return <Link href={href || '#'} className="stat-card"><div className={`stat-icon ${tone}`}>{tone === 'teal' ? '↗' : tone === 'blue' ? '↙' : tone === 'purple' ? '◫' : '◎'}</div><div className="stat-body"><span>{label}</span><strong>{Number(value || 0).toLocaleString('ar-EG')} <small>{unit}</small></strong><em>عرض التفاصيل ‹</em></div></Link>; }
function Activity({ title, detail }) { return <div className="activity-row"><div className="activity-icon teal">✓</div><div><strong>{title}</strong><span>{detail}</span></div></div>; }

export default function Dashboard({ metrics = {}, capabilities = {}, daily_sales = [], payments_receipts = {}, top_sold_products = [], sales_by_customer = [] }) {
    const { locale } = usePage().props;
    const t = (key) => translate(locale, key);
    const number = (value) => Number(value || 0).toLocaleString(locale === 'ar' ? 'ar-EG' : 'en-EG');
    return <CompanyLayout title={t('companyOverview')}>
        <section className="welcome-row"><div><div className="eyebrow">✦ {new Date().toLocaleDateString(locale === 'ar' ? 'ar-EG' : 'en-EG', { weekday: 'long', day: 'numeric', month: 'long' })}</div><h1>{locale === 'ar' ? 'مرحبًا بك في E‑Zaki' : 'Welcome to E‑Zaki'}</h1><p>{locale === 'ar' ? 'إليك ملخص أداء شركتك اليوم.' : 'Here is your company performance summary.'}</p></div><Link className="primary-button" href="/operations">+ {t('operations')}</Link></section>
        <div className="license-banner"><div className="license-symbol">✓</div><div className="license-copy"><strong>{t('subscriptionStatus')}</strong><span>{locale === 'ar' ? 'بياناتك وحسابك محميان ضمن مساحة شركتك.' : 'Your data is protected inside your company workspace.'}</span></div><Link href="/subscription">{t('settings')} ‹</Link></div>
        <section className="stats-grid"><>{capabilities['sales.view'] && <Stat label={t('monthly_sales')} value={metrics.monthly_sales} unit="ج.م" tone="teal" href="/operations#sales" />}</><>{capabilities['purchases.view'] && <Stat label={t('monthly_purchases')} value={metrics.monthly_purchases} unit="ج.م" tone="blue" href="/operations#purchases" />}</><>{capabilities['accounting.view'] && <Stat label={t('debtors')} value={metrics.debtors} unit="ج.م" tone="purple" href="/reports/debtors" />}</><>{capabilities['parties.view'] && <Stat label={t('parties')} value={metrics.parties} unit="جهة" tone="orange" href="/parties" />}</></section>
        <div className="content-grid"><section className="panel chart-panel"><div className="panel-heading"><div><h2>{t('dailySales')}</h2><span>{locale === 'ar' ? 'المبيعات اليومية المعتمدة' : 'Approved daily sales'}</span></div></div><div className="chart-legend"><span><i className="dot teal-dot" /> {t('sales')}</span></div><div className="chart"><div className="y-labels"><span>100k</span><span>75k</span><span>50k</span><span>25k</span><span>0</span></div><div className="chart-area"><div className="grid-lines" /><div className="x-labels">{daily_sales.slice(-7).map((item) => <span key={item.bill_date}>{item.bill_date}</span>)}</div><div className="chart-bars">{daily_sales.slice(-7).map((item) => <i key={item.bill_date} style={{ height: `${Math.max(5, Math.min(100, Number(item.total || 0) / 1000))}%` }} title={number(item.total)} />)}</div></div></div></section><section className="panel activity-panel"><div className="panel-heading"><div><h2>{locale === 'ar' ? 'ملخص مالي' : 'Financial summary'}</h2><span>{locale === 'ar' ? 'آخر البيانات المرحّلة' : 'Latest posted data'}</span></div></div><Activity title={t('payments')} detail={`${number(payments_receipts.payments)} ج.م`} /><Activity title={t('receipts')} detail={`${number(payments_receipts.receipts)} ج.م`} /><Activity title={t('topSoldProducts')} detail={`${top_sold_products.length} ${locale === 'ar' ? 'أصناف' : 'items'}`} /><Activity title={t('salesByCustomer')} detail={`${sales_by_customer.length} ${locale === 'ar' ? 'عملاء' : 'customers'}`} /></section></div>
        <section className="bottom-grid"><section className="panel quick-panel"><div className="panel-heading"><div><h2>{locale === 'ar' ? 'الوصول السريع' : 'Quick access'}</h2><span>{locale === 'ar' ? 'ابدأ من هنا' : 'Start here'}</span></div></div><div className="quick-actions">{capabilities['sales.create'] && <Link className="quick-action" href="/operations/sales/create"><div>↗</div><span>{t('sales')}</span>+</Link>}{capabilities['purchases.create'] && <Link className="quick-action" href="/operations/purchase/create"><div>↙</div><span>{t('purchases')}</span>+</Link>}{capabilities['parties.create'] && <Link className="quick-action" href="/parties"><div>◎</div><span>{t('parties')}</span>+</Link>}{capabilities['reports.view'] && <Link className="quick-action" href="/reports/journal"><div>◒</div><span>{t('reports')}</span>+</Link>}</div></section><section className="panel setup-panel"><div className="panel-heading"><div><h2>{locale === 'ar' ? 'حالة النظام' : 'System status'}</h2><span>{locale === 'ar' ? 'الوحدات المتاحة حسب صلاحياتك' : 'Modules available to you'}</span></div></div><div className="setup-row"><div className="check done">✓</div><span className="done-text">{t('companyOverview')}</span></div><div className="setup-row"><div className="check done">✓</div><span className="done-text">{t('accounting')}</span></div><div className="setup-row"><div className="check done">✓</div><span className="done-text">{t('inventory')}</span></div></section></section>
    </CompanyLayout>;
}
