import { useState } from 'react';
import { usePage } from '@inertiajs/react';
import CompanyLayout from '../../Layouts/CompanyLayout';
import { useCoreApi } from '../../useCoreApi';
import { translate } from '../../i18n';

const expenseCategories = ['fuel', 'maintenance', 'parts', 'oil', 'tires', 'tolls', 'loading', 'driver_wages', 'insurance', 'licensing', 'fines', 'other'];
const reportLinks = ['vehicle-pl', 'trip-cost', 'fuel', 'driver-performance', 'expenses-by-category', 'maintenance-period', 'inactive-vehicles', 'branch-performance'];
const dateValue = (value) => value ? String(value).slice(0, 10) : '';
const dateTimeValue = (value) => value ? String(value).slice(0, 16) : '';

export default function Fleet({ branches = [], vehicles, drivers, trips, expenses, maintenance, capabilities = {} }) {
    const { locale } = usePage().props;
    const ar = locale === 'ar';
    const t = (key) => translate(locale, key);
    const text = (arabic, english) => ar ? arabic : english;
    const { notice, processing, send } = useCoreApi();
    const [vehicle, setVehicle] = useState({ branch_id: '', plate: '', ownership: 'company', status: 'active', type: '', make_model: '', year: '', capacity: '', fuel_type: '', license_expires_at: '', insurance_expires_at: '', notes: '' });
    const [driver, setDriver] = useState({ name: '', phone: '', license_number: '', license_type: '', license_expires_at: '', status: 'active', notes: '' });
    const [trip, setTrip] = useState({ vehicle_id: '', driver_id: '', branch_id: '', trip_type: 'delivery', trip_at: '', origin: '', destination: '', distance: '', odometer_in: '', odometer_out: '', fuel_cost: 0, road_fees: 0, loading_fees: 0, revenue: 0, notes: '' });
    const [expense, setExpense] = useState({ vehicle_id: '', trip_id: '', expense_date: '', category: 'fuel', amount: 0, notes: '' });
    const [service, setService] = useState({ vehicle_id: '', maintenance_type: 'preventive', issue: '', parts: '', labor_cost: 0, parts_cost: 0, vendor: '', cost: 0, starts_on: '', ends_on: '', next_due_on: '', vehicle_status: 'in_service', notes: '' });
    const [editingVehicle, setEditingVehicle] = useState(null);
    const [editingDriver, setEditingDriver] = useState(null);
    const [editingTrip, setEditingTrip] = useState(null);
    const [editingExpense, setEditingExpense] = useState(null);
    const [editingService, setEditingService] = useState(null);
    const submit = (path, method, value) => send(path, method, value);
    const status = (value) => text({ active: 'نشطة', inactive: 'غير نشطة', draft: 'مسودة', approved: 'معتمدة', reversed: 'معكوسة' }[value] ?? value, value);

    return <CompanyLayout title={t('fleet')}>
        <h1 className="text-2xl font-semibold">{t('fleet')}</h1>
        {notice.message && <p role="alert" className="mt-4 border-l-4 border-[#34795c] bg-white p-3 text-sm">{notice.message}</p>}

        {capabilities['fleet.create'] && <div className="mt-6 grid gap-6 lg:grid-cols-2">
            <form onSubmit={(event) => { event.preventDefault(); submit(editingVehicle ? `fleet/vehicles/${editingVehicle.id}` : 'fleet/vehicles', editingVehicle ? 'PUT' : 'POST', vehicle); }} className="grid gap-2 border-t border-[#d7ddd5] pt-4 sm:grid-cols-2">
                <h2 className="font-semibold sm:col-span-2">{editingVehicle ? text('تعديل مركبة', 'Edit vehicle') : text('مركبة جديدة', 'New vehicle')}</h2>
                <select value={vehicle.branch_id ?? ''} onChange={(event) => setVehicle({ ...vehicle, branch_id: event.target.value })} className="border p-2"><option value="">{text('بدون فرع', 'No branch')}</option>{branches.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select>
                <input required placeholder={text('رقم اللوحة', 'Plate')} value={vehicle.plate} onChange={(event) => setVehicle({ ...vehicle, plate: event.target.value })} className="border p-2" />
                <input placeholder={text('النوع', 'Type')} value={vehicle.type ?? ''} onChange={(event) => setVehicle({ ...vehicle, type: event.target.value })} className="border p-2" />
                <input placeholder={text('الماركة / الموديل', 'Make / model')} value={vehicle.make_model ?? ''} onChange={(event) => setVehicle({ ...vehicle, make_model: event.target.value })} className="border p-2" />
                <input type="number" min="1900" max="2100" placeholder={text('سنة الصنع', 'Year')} value={vehicle.year ?? ''} onChange={(event) => setVehicle({ ...vehicle, year: event.target.value })} className="border p-2" />
                <input type="number" min="0" step="0.001" placeholder={text('الحمولة', 'Capacity')} value={vehicle.capacity ?? ''} onChange={(event) => setVehicle({ ...vehicle, capacity: event.target.value })} className="border p-2" />
                <input placeholder={text('نوع الوقود', 'Fuel type')} value={vehicle.fuel_type ?? ''} onChange={(event) => setVehicle({ ...vehicle, fuel_type: event.target.value })} className="border p-2" />
                <select value={vehicle.ownership} onChange={(event) => setVehicle({ ...vehicle, ownership: event.target.value })} className="border p-2"><option value="company">{text('مملوكة للشركة', 'Company')}</option><option value="rented">{text('مؤجرة', 'Rented')}</option><option value="external">{text('خارجية', 'External')}</option></select>
                <select value={vehicle.status} onChange={(event) => setVehicle({ ...vehicle, status: event.target.value })} className="border p-2"><option value="active">{text('نشطة', 'Active')}</option><option value="inactive">{text('غير نشطة', 'Inactive')}</option></select>
                <label className="grid gap-1 text-sm">{text('انتهاء الرخصة', 'License expiry')}<input type="date" value={dateValue(vehicle.license_expires_at)} onChange={(event) => setVehicle({ ...vehicle, license_expires_at: event.target.value })} className="border p-2" /></label>
                <label className="grid gap-1 text-sm">{text('انتهاء التأمين', 'Insurance expiry')}<input type="date" value={dateValue(vehicle.insurance_expires_at)} onChange={(event) => setVehicle({ ...vehicle, insurance_expires_at: event.target.value })} className="border p-2" /></label>
                <textarea placeholder={t('notes')} value={vehicle.notes ?? ''} onChange={(event) => setVehicle({ ...vehicle, notes: event.target.value })} className="border p-2 sm:col-span-2" />
                <button disabled={processing} className="bg-[#34795c] px-3 py-2 text-white sm:col-span-2">{text('حفظ المركبة', 'Save vehicle')}</button>
            </form>
            <form onSubmit={(event) => { event.preventDefault(); submit(editingDriver ? `fleet/drivers/${editingDriver.id}` : 'fleet/drivers', editingDriver ? 'PUT' : 'POST', driver); }} className="grid gap-2 border-t border-[#d7ddd5] pt-4 sm:grid-cols-2">
                <h2 className="font-semibold sm:col-span-2">{editingDriver ? text('تعديل سائق', 'Edit driver') : text('سائق جديد', 'New driver')}</h2>
                <input required placeholder={text('الاسم', 'Name')} value={driver.name} onChange={(event) => setDriver({ ...driver, name: event.target.value })} className="border p-2" />
                <input placeholder={t('phone')} value={driver.phone ?? ''} onChange={(event) => setDriver({ ...driver, phone: event.target.value })} className="border p-2" />
                <input placeholder={text('رقم الرخصة', 'License number')} value={driver.license_number ?? ''} onChange={(event) => setDriver({ ...driver, license_number: event.target.value })} className="border p-2" />
                <input placeholder={text('نوع الرخصة', 'License type')} value={driver.license_type ?? ''} onChange={(event) => setDriver({ ...driver, license_type: event.target.value })} className="border p-2" />
                <input type="date" aria-label={text('انتهاء الرخصة', 'License expiry')} value={dateValue(driver.license_expires_at)} onChange={(event) => setDriver({ ...driver, license_expires_at: event.target.value })} className="border p-2" />
                <select value={driver.status} onChange={(event) => setDriver({ ...driver, status: event.target.value })} className="border p-2"><option value="active">{text('نشط', 'Active')}</option><option value="inactive">{text('غير نشط', 'Inactive')}</option></select>
                <textarea placeholder={t('notes')} value={driver.notes ?? ''} onChange={(event) => setDriver({ ...driver, notes: event.target.value })} className="border p-2 sm:col-span-2" />
                <button disabled={processing} className="bg-[#34795c] px-3 py-2 text-white sm:col-span-2">{text('حفظ السائق', 'Save driver')}</button>
            </form>
        </div>}

        <section className="mt-8 grid gap-6 lg:grid-cols-2"><div><h2 className="font-semibold">{text('المركبات', 'Vehicles')}</h2>{vehicles.data.map((item) => <div key={item.id} className="mt-2 flex justify-between border-b py-2 text-sm"><span>{item.plate} · {status(item.status)}</span>{capabilities['fleet.update'] && <button onClick={() => { setEditingVehicle(item); setVehicle({ ...vehicle, ...item }); }} className="underline">{t('edit')}</button>}</div>)}</div><div><h2 className="font-semibold">{text('السائقون', 'Drivers')}</h2>{drivers.data.map((item) => <div key={item.id} className="mt-2 flex justify-between border-b py-2 text-sm"><span>{item.name} · {status(item.status)}</span>{capabilities['fleet.update'] && <button onClick={() => { setEditingDriver(item); setDriver({ ...driver, ...item }); }} className="underline">{t('edit')}</button>}</div>)}</div></section>

        <div className="no-print mt-8 flex flex-wrap gap-3 text-sm">{reportLinks.map((report) => <a key={report} href={`/fleet/reports/${report}`} className="border border-[#34795c] px-3 py-2">{text({ 'vehicle-pl': 'ربحية المركبات', 'trip-cost': 'تكلفة الرحلات', fuel: 'الوقود', 'driver-performance': 'أداء السائقين', 'expenses-by-category': 'المصروفات', 'maintenance-period': 'الصيانة', 'inactive-vehicles': 'غير النشطة', 'branch-performance': 'أداء الفروع' }[report], report)}</a>)}</div>

        <section className="mt-8 grid gap-6 lg:grid-cols-2"><div><h2 className="font-semibold">{t('trips')}</h2>{trips.data.map((item) => <p key={item.id} className="mt-2 border-b py-2 text-sm">{item.vehicle?.plate} · {item.trip_type} · {status(item.status)}{item.status === 'draft' && capabilities['fleet.update'] && <button onClick={() => { setEditingTrip(item); setTrip({ ...trip, ...item, trip_at: dateTimeValue(item.trip_at) }); }} className="ms-3 underline">{t('edit')}</button>}</p>)}</div><div><h2 className="font-semibold">{text('المصروفات', 'Expenses')}</h2>{expenses.data.map((item) => <p key={item.id} className="mt-2 border-b py-2 text-sm">{item.category} · {item.amount} · {status(item.status)}{item.status === 'draft' && capabilities['fleet.expenses'] && <button onClick={() => { setEditingExpense(item); setExpense({ ...expense, ...item, expense_date: dateValue(item.expense_date) }); }} className="ms-3 underline">{t('edit')}</button>}{item.status === 'draft' && capabilities['fleet.approve'] && <button onClick={() => submit(`fleet/expenses/${item.id}/approve`, 'POST')} className="ms-3 underline">{t('approve')}</button>}{item.status === 'approved' && capabilities['fleet.approve'] && <button onClick={() => submit(`fleet/expenses/${item.id}/reverse`, 'POST', { date: new Date().toISOString().slice(0, 10) })} className="ms-3 underline">{t('reverse')}</button>}</p>)}</div></section>

        {capabilities['fleet.maintenance'] && <section className="mt-8"><h2 className="font-semibold">{text('الصيانة', 'Maintenance')}</h2>{maintenance.data.map((item) => <p key={item.id} className="mt-2 border-b py-2 text-sm">{item.issue} · {item.cost} · {status(item.status)}{item.status === 'draft' && <button onClick={() => { setEditingService(item); setService({ ...service, ...item, starts_on: dateValue(item.starts_on), ends_on: dateValue(item.ends_on), next_due_on: dateValue(item.next_due_on) }); }} className="ms-3 underline">{t('edit')}</button>}{item.status === 'draft' && capabilities['fleet.approve'] && <button onClick={() => submit(`fleet/maintenance/${item.id}/approve`, 'POST')} className="ms-3 underline">{t('approve')}</button>}{item.status === 'approved' && capabilities['fleet.approve'] && <button onClick={() => submit(`fleet/maintenance/${item.id}/reverse`, 'POST', { date: new Date().toISOString().slice(0, 10) })} className="ms-3 underline">{t('reverse')}</button>}</p>)}</section>}

        <section className="mt-8 grid gap-6 border-t border-[#d7ddd5] pt-5 lg:grid-cols-3">
            {capabilities['fleet.create'] && <form onSubmit={(event) => { event.preventDefault(); submit(editingTrip ? `fleet/trips/${editingTrip.id}` : 'fleet/trips', editingTrip ? 'PUT' : 'POST', trip); }} className="grid gap-2"><h2 className="font-semibold">{editingTrip ? text('تعديل رحلة', 'Edit trip') : text('رحلة جديدة', 'New trip')}</h2><select required value={trip.vehicle_id} onChange={(event) => setTrip({ ...trip, vehicle_id: event.target.value })} className="border p-2"><option value="">{text('المركبة', 'Vehicle')}</option>{vehicles.data.map((item) => <option key={item.id} value={item.id}>{item.plate}</option>)}</select><select value={trip.driver_id ?? ''} onChange={(event) => setTrip({ ...trip, driver_id: event.target.value })} className="border p-2"><option value="">{text('السائق', 'Driver')}</option>{drivers.data.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select value={trip.branch_id ?? ''} onChange={(event) => setTrip({ ...trip, branch_id: event.target.value })} className="border p-2"><option value="">{text('الفرع', 'Branch')}</option>{branches.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><input required placeholder={text('نوع الرحلة', 'Trip type')} value={trip.trip_type} onChange={(event) => setTrip({ ...trip, trip_type: event.target.value })} className="border p-2" /><input required type="datetime-local" value={trip.trip_at} onChange={(event) => setTrip({ ...trip, trip_at: event.target.value })} className="border p-2" /><input placeholder={text('من', 'Origin')} value={trip.origin ?? ''} onChange={(event) => setTrip({ ...trip, origin: event.target.value })} className="border p-2" /><input placeholder={text('إلى', 'Destination')} value={trip.destination ?? ''} onChange={(event) => setTrip({ ...trip, destination: event.target.value })} className="border p-2" />{['distance', 'odometer_in', 'odometer_out', 'fuel_cost', 'road_fees', 'loading_fees', 'revenue'].map((field) => <input key={field} type="number" min="0" step="0.01" placeholder={field.replaceAll('_', ' ')} value={trip[field] ?? ''} onChange={(event) => setTrip({ ...trip, [field]: event.target.value })} className="border p-2" />)}<textarea placeholder={t('notes')} value={trip.notes ?? ''} onChange={(event) => setTrip({ ...trip, notes: event.target.value })} className="border p-2" /><button disabled={processing} className="bg-[#34795c] px-3 py-2 text-white">{text('حفظ الرحلة', 'Save trip')}</button></form>}
            {capabilities['fleet.expenses'] && <form onSubmit={(event) => { event.preventDefault(); submit(editingExpense ? `fleet/expenses/${editingExpense.id}` : 'fleet/expenses', editingExpense ? 'PUT' : 'POST', expense); }} className="grid gap-2"><h2 className="font-semibold">{editingExpense ? text('تعديل مصروف', 'Edit expense') : text('مصروف جديد', 'New expense')}</h2><select required value={expense.vehicle_id} onChange={(event) => setExpense({ ...expense, vehicle_id: event.target.value })} className="border p-2"><option value="">{text('المركبة', 'Vehicle')}</option>{vehicles.data.map((item) => <option key={item.id} value={item.id}>{item.plate}</option>)}</select><select value={expense.trip_id ?? ''} onChange={(event) => setExpense({ ...expense, trip_id: event.target.value })} className="border p-2"><option value="">{text('بدون رحلة', 'No trip')}</option>{trips.data.map((item) => <option key={item.id} value={item.id}>{item.vehicle?.plate} · {item.trip_type}</option>)}</select><select value={expense.category} onChange={(event) => setExpense({ ...expense, category: event.target.value })} className="border p-2">{expenseCategories.map((category) => <option key={category} value={category}>{category}</option>)}</select><input required type="date" value={expense.expense_date} onChange={(event) => setExpense({ ...expense, expense_date: event.target.value })} className="border p-2" /><input required type="number" min="0.01" step="0.01" value={expense.amount} onChange={(event) => setExpense({ ...expense, amount: event.target.value })} className="border p-2" /><textarea placeholder={t('notes')} value={expense.notes ?? ''} onChange={(event) => setExpense({ ...expense, notes: event.target.value })} className="border p-2" /><button disabled={processing} className="bg-[#34795c] px-3 py-2 text-white">{text('حفظ المصروف', 'Save expense')}</button></form>}
            {capabilities['fleet.maintenance'] && <form onSubmit={(event) => { event.preventDefault(); submit(editingService ? `fleet/maintenance/${editingService.id}` : 'fleet/maintenance', editingService ? 'PUT' : 'POST', service); }} className="grid gap-2"><h2 className="font-semibold">{editingService ? text('تعديل صيانة', 'Edit maintenance') : text('صيانة جديدة', 'New maintenance')}</h2><select required value={service.vehicle_id} onChange={(event) => setService({ ...service, vehicle_id: event.target.value })} className="border p-2"><option value="">{text('المركبة', 'Vehicle')}</option>{vehicles.data.map((item) => <option key={item.id} value={item.id}>{item.plate}</option>)}</select><select value={service.maintenance_type} onChange={(event) => setService({ ...service, maintenance_type: event.target.value })} className="border p-2"><option value="preventive">{text('وقائية', 'Preventive')}</option><option value="emergency">{text('طارئة', 'Emergency')}</option></select><input required placeholder={text('العطل / العمل', 'Issue')} value={service.issue} onChange={(event) => setService({ ...service, issue: event.target.value })} className="border p-2" /><textarea placeholder={text('قطع الغيار', 'Parts')} value={service.parts ?? ''} onChange={(event) => setService({ ...service, parts: event.target.value })} className="border p-2" />{['labor_cost', 'parts_cost', 'cost'].map((field) => <input key={field} required={field === 'cost'} type="number" min="0" step="0.01" placeholder={field.replaceAll('_', ' ')} value={service[field] ?? ''} onChange={(event) => setService({ ...service, [field]: event.target.value })} className="border p-2" />)}<input placeholder={text('المورد / الورشة', 'Vendor')} value={service.vendor ?? ''} onChange={(event) => setService({ ...service, vendor: event.target.value })} className="border p-2" /><input required type="date" value={service.starts_on} onChange={(event) => setService({ ...service, starts_on: event.target.value })} className="border p-2" /><input type="date" value={service.ends_on ?? ''} onChange={(event) => setService({ ...service, ends_on: event.target.value })} className="border p-2" /><input type="date" value={service.next_due_on ?? ''} onChange={(event) => setService({ ...service, next_due_on: event.target.value })} className="border p-2" /><select value={service.vehicle_status} onChange={(event) => setService({ ...service, vehicle_status: event.target.value })} className="border p-2"><option value="in_service">{text('في الخدمة', 'In service')}</option><option value="out_of_service">{text('خارج الخدمة', 'Out of service')}</option></select><textarea placeholder={t('notes')} value={service.notes ?? ''} onChange={(event) => setService({ ...service, notes: event.target.value })} className="border p-2" /><button disabled={processing} className="bg-[#34795c] px-3 py-2 text-white">{text('حفظ الصيانة', 'Save maintenance')}</button></form>}
        </section>
    </CompanyLayout>;
}
