import { useState } from 'react';
import { usePage } from '@inertiajs/react';
import CompanyLayout from '../../Layouts/CompanyLayout';
import { translate } from '../../i18n';
import { useCoreApi } from '../../useCoreApi';

export default function Inventory({ rows, diameter_columns: matrixDiameters, column_totals: columnTotals, total_quantity: totalQuantity, warehouses, productTypes, diameters, capabilities = {} }) {
    const { locale } = usePage().props;
    const t = (key) => translate(locale, key);
    const { notice, processing, send } = useCoreApi();
    const [warehouseId, setWarehouseId] = useState('');
    const [typeName, setTypeName] = useState('');
    const [diameter, setDiameter] = useState('');
    const [profile, setProfile] = useState({ warehouse_id: '', product_type_id: '', diameter_id: '', opening_balance: '', minimum_stock: '' });

    return <CompanyLayout title={t('inventory')}>
        <h1 className="text-2xl font-semibold">{t('inventory')}</h1>
        {notice.message && <p role="status" className="mt-4 border-l-4 bg-white p-3 text-sm">{notice.message}</p>}
        <div className="mt-6 flex flex-wrap items-end gap-3"><label className="text-sm" title={t('warehouse')}>{t('warehouse')}<select title={t('warehouse')} value={warehouseId} onChange={(event) => setWarehouseId(event.target.value)} className="mt-1 block min-w-56 border px-3 py-2"><option value="">{t('allWarehouses')}</option>{warehouses.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><a href={`/inventory${warehouseId ? `?warehouse_id=${warehouseId}` : ''}`} className="border border-[#34795c] px-4 py-2 text-sm">{t('filter')}</a></div>
        {capabilities['products.create'] && <section className="mt-8 grid gap-4 border-t border-[#d7ddd5] pt-5 sm:grid-cols-2"><form onSubmit={(event) => { event.preventDefault(); send('product-types', 'POST', { name: typeName }); }} className="flex gap-2"><input required title={t('productTypes')} placeholder={t('productTypes')} value={typeName} onChange={(event) => setTypeName(event.target.value)} className="min-w-0 flex-1 border px-3 py-2" /><button disabled={processing} className="border border-[#34795c] px-3 py-2">{t('addType')}</button></form><form onSubmit={(event) => { event.preventDefault(); send('diameters', 'POST', { millimeters: diameter }); }} className="flex gap-2"><input required title={t('diameters')} placeholder={t('diameters')} type="number" min="1" step="0.5" value={diameter} onChange={(event) => setDiameter(event.target.value)} className="min-w-0 flex-1 border px-3 py-2" /><button disabled={processing} className="border border-[#34795c] px-3 py-2">{t('addDiameter')}</button></form><form onSubmit={(event) => { event.preventDefault(); send('inventory/type-diameter-profile', 'POST', profile); }} className="grid gap-2 border-t border-[#d7ddd5] pt-4 sm:col-span-2 sm:grid-cols-3"><select required aria-label={t('warehouse')} value={profile.warehouse_id} onChange={(event) => setProfile({ ...profile, warehouse_id: event.target.value })} className="border px-3 py-2"><option value="">{t('warehouse')}</option>{warehouses.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select required aria-label={t('productTypes')} value={profile.product_type_id} onChange={(event) => setProfile({ ...profile, product_type_id: event.target.value })} className="border px-3 py-2"><option value="">{t('productTypes')}</option>{productTypes.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select required aria-label={t('diameters')} value={profile.diameter_id} onChange={(event) => setProfile({ ...profile, diameter_id: event.target.value })} className="border px-3 py-2"><option value="">{t('diameters')}</option>{diameters.map((item) => <option key={item.id} value={item.id}>{item.millimeters} mm</option>)}</select><input aria-label={t('openingAmount')} type="number" min="0" step="0.001" placeholder={t('openingAmount')} value={profile.opening_balance} onChange={(event) => setProfile({ ...profile, opening_balance: event.target.value })} className="border px-3 py-2" /><input aria-label={t('minimumStock')} type="number" min="0" step="0.001" placeholder={t('minimumStock')} value={profile.minimum_stock} onChange={(event) => setProfile({ ...profile, minimum_stock: event.target.value })} className="border px-3 py-2" /><button disabled={processing} className="border border-[#34795c] px-3 py-2">{t('save')}</button></form></section>}
        <div className="mt-5 overflow-x-auto"><table className="w-full min-w-[700px] border-collapse text-left text-sm"><thead><tr className="border-y"><th className="py-3">{t('type')}</th>{matrixDiameters.map((item) => <th key={item} className="py-3">{item} mm</th>)}<th className="py-3">{t('total')}</th></tr></thead><tbody>{rows.map((row) => <tr key={row.key} className="border-b"><td className="py-3">{row.type}</td>{matrixDiameters.map((item) => <td key={item} className="py-3">{Number(row.cells[item] ?? 0).toLocaleString()}</td>)}<td className="py-3 font-medium">{Number(row.total).toLocaleString()}</td></tr>)}</tbody><tfoot><tr className="border-t-2 font-semibold"><td className="py-3">{t('companyTotals')}</td>{matrixDiameters.map((item) => <td key={item} className="py-3">{Number(columnTotals[item] ?? 0).toLocaleString()}</td>)}<td className="py-3">{Number(totalQuantity).toLocaleString()}</td></tr></tfoot></table>{rows.length === 0 && <p className="py-4 text-sm">{t('noRecords')}</p>}</div>
        <div className="mt-6 grid gap-2 text-sm"><p>{t('productTypes')}: {productTypes.map((item) => item.name).join(', ') || t('noRecords')}</p><p>{t('diameters')}: {diameters.map((item) => `${item.millimeters} mm`).join(', ') || t('noRecords')}</p></div>
    </CompanyLayout>;
}
