import { Link, usePage } from '@inertiajs/react';
import CompanyLayout from '../../Layouts/CompanyLayout';
import { translate } from '../../i18n';

export default function Operations({ purchases, sales, vehicles, trips, capabilities = {} }) {
    const { locale } = usePage().props;
    const t = (key) => translate(locale, key);
    const statusLabel = (status) => ({ draft: t('draft'), approved: t('approved'), reversed: t('reversed') }[status] ?? status);

    return <CompanyLayout title={t('operations')}>
        <div className="flex flex-wrap items-end justify-between gap-4">
            <div><p className="text-xs uppercase text-[#68736b]">{t('companyWorkspace')}</p><h1 className="mt-1 text-2xl font-semibold">{t('operations')}</h1></div>
            <div className="flex gap-3 text-sm">{capabilities['purchases.create'] && <Link href="/operations/purchase/create" className="border border-[#34795c] px-3 py-2">{t('purchases')}</Link>}{capabilities['sales.create'] && <Link href="/operations/sales/create" className="border border-[#34795c] px-3 py-2">{t('sales')}</Link>}{capabilities['fleet.view'] && <Link href="#fleet" className="border border-[#34795c] px-3 py-2">{t('fleet')}</Link>}</div>
        </div>
        {capabilities['purchases.view'] && <section id="purchases" className="mt-8 border-t border-[#d7ddd5] pt-5"><h2 className="font-semibold">{t('purchases')}</h2><div className="mt-3 overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead><tr className="border-y border-[#d7ddd5]"><th className="py-3">{t('internalNumber')}</th><th className="py-3">{t('supplier')}</th><th className="py-3">{t('total')}</th><th className="py-3">{t('status')}</th><th className="py-3">{t('actions')}</th></tr></thead><tbody>{purchases.data.map((bill) => <tr key={bill.id} className="border-b border-[#d7ddd5]"><td className="py-3">{bill.internal_number}</td><td className="py-3">{bill.supplier?.name}</td><td className="py-3">{bill.total}</td><td className="py-3">{statusLabel(bill.status)}</td><td className="flex flex-wrap gap-3 py-3"><Link href={`/operations/purchase/${bill.id}`} className="font-semibold text-[#34795c]">{t('view')}</Link>{((bill.status === 'draft' && capabilities['purchases.update']) || (bill.status === 'approved' && capabilities['purchases.update_approved'])) && <Link href={`/operations/purchase/${bill.id}/edit`} className="underline">{t('edit')}</Link>}{bill.status === 'draft' && capabilities['purchases.approve'] && <Link href={`/operations/purchase/${bill.id}/edit`} className="font-semibold text-[#a64b36]">{t('approve')}</Link>}{capabilities['purchases.print'] && <><a href={`/operations/purchase/${bill.id}/print?mode=invoice`} className="underline">{t('printInvoice')}</a><a href={`/operations/purchase/${bill.id}/print?mode=delivery`} className="underline">{t('printOperational')}</a></>}{capabilities['purchases.export'] && <a href={`/operations/purchase/${bill.id}/export`} className="underline">{t('exportCsv')}</a>}</td></tr>)}</tbody></table></div></section>}
        {capabilities['sales.view'] && <section id="sales" className="mt-8 border-t border-[#d7ddd5] pt-5"><h2 className="font-semibold">{t('sales')}</h2><div className="mt-3 overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead><tr className="border-y border-[#d7ddd5]"><th className="py-3">{t('internalNumber')}</th><th className="py-3">{t('customer')}</th><th className="py-3">{t('total')}</th><th className="py-3">{t('status')}</th><th className="py-3">{t('actions')}</th></tr></thead><tbody>{sales.data.map((bill) => <tr key={bill.id} className="border-b border-[#d7ddd5]"><td className="py-3">{bill.internal_number}</td><td className="py-3">{bill.customer?.name}</td><td className="py-3">{bill.total}</td><td className="py-3">{statusLabel(bill.status)}</td><td className="flex flex-wrap gap-3 py-3"><Link href={`/operations/sales/${bill.id}`} className="font-semibold text-[#34795c]">{t('view')}</Link>{((bill.status === 'draft' && capabilities['sales.update']) || (bill.status === 'approved' && capabilities['sales.update_approved'])) && <Link href={`/operations/sales/${bill.id}/edit`} className="underline">{t('edit')}</Link>}{bill.status === 'draft' && capabilities['sales.approve'] && <Link href={`/operations/sales/${bill.id}/edit`} className="font-semibold text-[#a64b36]">{t('approve')}</Link>}{capabilities['sales.print'] && <><a href={`/operations/sales/${bill.id}/print?mode=invoice`} className="underline">{t('printInvoice')}</a><a href={`/operations/sales/${bill.id}/print?mode=delivery`} className="underline">{t('printOperational')}</a></>}{capabilities['sales.export'] && <a href={`/operations/sales/${bill.id}/export`} className="underline">{t('exportCsv')}</a>}</td></tr>)}</tbody></table></div></section>}
        {capabilities['fleet.view'] && <section id="fleet" className="mt-8 border-t border-[#d7ddd5] pt-5"><h2 className="font-semibold">{t('fleet')}</h2><div className="mt-3 grid gap-3 md:grid-cols-2">{vehicles.map((vehicle) => <div key={vehicle.id} className="border border-[#d7ddd5] bg-white p-4 text-sm"><strong>{vehicle.plate}</strong><span className="ml-3 text-[#68736b]">{vehicle.ownership}</span></div>)}</div><h3 className="mt-6 font-semibold">{t('trips')}</h3><div className="mt-2 divide-y divide-[#d7ddd5] border-y border-[#d7ddd5]">{trips.map((trip) => <p key={trip.id} className="py-2 text-sm">{trip.vehicle?.plate} · {trip.trip_type} · {trip.status}</p>)}</div></section>}
    </CompanyLayout>;
}
