import { useState } from 'react';
import { Link, usePage } from '@inertiajs/react';
import CompanyLayout from '../../Layouts/CompanyLayout';
import { translate } from '../../i18n';
import { useCoreApi } from '../../useCoreApi';

export default function Parties({ parties, accounts, kind = null, capabilities = {} }) {
    const { locale } = usePage().props;
    const t = (key) => translate(locale, key);
    const { notice, processing, send } = useCoreApi();
    const [form, setForm] = useState({ name: '', parent_account_id: '', email: '', phone: '', tax_number: '', address: '', is_customer: true, is_supplier: false, opening_balance: '0', credit_limit: '' });
    const [editing, setEditing] = useState(null);

    return <CompanyLayout title={t('parties')}>
        <h1 className="text-2xl font-semibold">{kind === 'customer' ? t('customers') : kind === 'supplier' ? t('suppliers') : t('parties')}</h1>
        {notice.message && <p role="status" className={`mt-4 border-l-4 bg-white p-3 text-sm ${notice.type === 'error' ? 'border-red-700' : 'border-[#34795c]'}`}>{notice.message}</p>}
        <div className="mt-6 overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead><tr className="border-y border-[#d7ddd5]"><th className="py-3">{t('customerSupplier')}</th><th className="py-3">{t('accountCode')}</th><th className="py-3">{t('email')}</th><th className="py-3">Type</th><th className="py-3">{t('openingAmount')}</th><th className="py-3">Statement</th><th className="py-3">{kind === 'supplier' ? t('postVoucher') : t('postReceipt')}</th>{capabilities['parties.update'] && <th className="py-3">{t('edit')}</th>}</tr></thead><tbody>{parties.data.map((party) => <tr key={party.id} className="border-b border-[#d7ddd5]"><td className="py-3">{party.name}</td><td className="py-3">{party.account?.code}</td><td className="py-3">{party.email ?? '-'}</td><td className="py-3">{[party.is_customer && t('isCustomer'), party.is_supplier && t('isSupplier')].filter(Boolean).join(' / ')}</td><td className="py-3">{party.opening_balance}</td><td className="py-3"><Link className="underline" href={`/reports/account-statement?account_id=${party.account_id}`}>{t('accountStatement')}</Link></td><td className="py-3"><Link className="underline" href={`/accounting?counterparty_type=${kind === 'supplier' ? 'supplier' : 'customer'}&party_id=${party.id}`}>{kind === 'supplier' ? t('postVoucher') : t('postReceipt')}</Link></td>{capabilities['parties.update'] && <td className="py-3"><button onClick={() => setEditing({ id: party.id, name: party.name, parent_account_id: party.parent_account_id, email: party.email ?? '', phone: party.phone ?? '', tax_number: party.tax_number ?? '', address: party.address ?? '', is_customer: party.is_customer, is_supplier: party.is_supplier, opening_balance: party.opening_balance, credit_limit: party.credit_limit ?? '' })} className="underline">{t('edit')}</button></td>}</tr>)}</tbody></table>{parties.data.length === 0 && <p className="py-4 text-sm text-[#637067]">{t('noRecords')}</p>}</div>
        {capabilities['parties.create'] && <section className="mt-8 max-w-4xl border-t border-[#d7ddd5] pt-5"><h2 className="font-semibold">{t('createParty')}</h2><form onSubmit={(event) => { event.preventDefault(); send('parties', 'POST', form); }} className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
            <input required aria-label={t('customerSupplier')} placeholder={t('customerSupplier')} value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} className="border border-[#c9d0c8] bg-white px-3 py-2" />
            <select required aria-label={t('parentAccount')} value={form.parent_account_id} onChange={(event) => setForm({ ...form, parent_account_id: event.target.value })} className="border border-[#c9d0c8] bg-white px-3 py-2"><option value="">{t('parentAccount')}</option>{accounts.map((account) => <option key={account.id} value={account.id}>{account.code} · {account.name}</option>)}</select>
            <input aria-label={t('email')} type="email" placeholder={t('email')} value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} className="border border-[#c9d0c8] bg-white px-3 py-2" />
            <input aria-label={t('phone')} placeholder={t('phone')} value={form.phone} onChange={(event) => setForm({ ...form, phone: event.target.value })} className="border border-[#c9d0c8] bg-white px-3 py-2" />
            <input aria-label={t('taxNumber')} placeholder={t('taxNumber')} value={form.tax_number} onChange={(event) => setForm({ ...form, tax_number: event.target.value })} className="border border-[#c9d0c8] bg-white px-3 py-2" />
            <input aria-label={t('address')} placeholder={t('address')} value={form.address} onChange={(event) => setForm({ ...form, address: event.target.value })} className="border border-[#c9d0c8] bg-white px-3 py-2" />
            <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.is_customer} onChange={(event) => setForm({ ...form, is_customer: event.target.checked })} />{t('isCustomer')}</label>
            <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.is_supplier} onChange={(event) => setForm({ ...form, is_supplier: event.target.checked })} />{t('isSupplier')}</label>
            <input aria-label={t('openingAmount')} type="number" step="0.01" placeholder={t('openingAmount')} value={form.opening_balance} onChange={(event) => setForm({ ...form, opening_balance: event.target.value })} className="border border-[#c9d0c8] bg-white px-3 py-2" />
            <input aria-label={t('creditLimit')} type="number" min="0" step="0.01" placeholder={t('creditLimit')} value={form.credit_limit} onChange={(event) => setForm({ ...form, credit_limit: event.target.value })} className="border border-[#c9d0c8] bg-white px-3 py-2" />
            <button disabled={processing} className="bg-[#34795c] px-4 py-2 text-white sm:col-span-2 lg:col-span-3">{t('createParty')}</button>
        </form></section>}
        {editing && <div className="fixed inset-0 z-20 grid place-items-center bg-black/40 p-4"><form onSubmit={(event) => { event.preventDefault(); send(`parties/${editing.id}`, 'PUT', editing); }} className="max-h-[90vh] w-full max-w-2xl overflow-y-auto bg-white p-6"><h2 className="text-lg font-semibold">{t('edit')} · {editing.name}</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><input required aria-label={t('customerSupplier')} value={editing.name} onChange={(event) => setEditing({ ...editing, name: event.target.value })} className="border border-[#c9d0c8] px-3 py-2" /><select required aria-label={t('parentAccount')} value={editing.parent_account_id} onChange={(event) => setEditing({ ...editing, parent_account_id: event.target.value })} className="border border-[#c9d0c8] bg-white px-3 py-2">{accounts.map((account) => <option key={account.id} value={account.id}>{account.code} · {account.name}</option>)}</select><input aria-label={t('email')} type="email" value={editing.email} onChange={(event) => setEditing({ ...editing, email: event.target.value })} className="border border-[#c9d0c8] px-3 py-2" /><input aria-label={t('phone')} value={editing.phone} onChange={(event) => setEditing({ ...editing, phone: event.target.value })} className="border border-[#c9d0c8] px-3 py-2" /><input aria-label={t('taxNumber')} value={editing.tax_number} onChange={(event) => setEditing({ ...editing, tax_number: event.target.value })} className="border border-[#c9d0c8] px-3 py-2" /><input aria-label={t('address')} value={editing.address} onChange={(event) => setEditing({ ...editing, address: event.target.value })} className="border border-[#c9d0c8] px-3 py-2" /><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={editing.is_customer} onChange={(event) => setEditing({ ...editing, is_customer: event.target.checked })} />{t('isCustomer')}</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={editing.is_supplier} onChange={(event) => setEditing({ ...editing, is_supplier: event.target.checked })} />{t('isSupplier')}</label><input aria-label={t('openingAmount')} type="number" step="0.01" value={editing.opening_balance} onChange={(event) => setEditing({ ...editing, opening_balance: event.target.value })} className="border border-[#c9d0c8] px-3 py-2" /><input aria-label={t('creditLimit')} type="number" min="0" step="0.01" value={editing.credit_limit} onChange={(event) => setEditing({ ...editing, credit_limit: event.target.value })} className="border border-[#c9d0c8] px-3 py-2" /></div><div className="mt-5 flex gap-3"><button className="bg-[#34795c] px-4 py-2 text-white">{t('saveChanges')}</button><button type="button" onClick={() => setEditing(null)} className="underline">Cancel</button></div></form></div>}
    </CompanyLayout>;
}