import { Link } from '@inertiajs/react';
import { useState } from 'react';
import CompanyLayout from '../../Layouts/CompanyLayout';
import { useCoreApi } from '../../useCoreApi';

export default function UserProfile({ profile, roles }) {
    const { notice, processing, send } = useCoreApi();
    const [form, setForm] = useState({ first_name: profile.first_name ?? '', second_name: profile.second_name ?? '', email: profile.email ?? '', current_password: '', password: '', password_confirmation: '' });
    const update = (key, value) => setForm({ ...form, [key]: value });
    return <CompanyLayout title={`Profile: ${profile.name}`}>
        <div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs uppercase text-[#637067]">User profile</p><h1 className="mt-2 text-2xl font-semibold">{profile.name}</h1><p className="mt-1 text-sm text-[#637067]">{profile.email}</p></div><div className="flex gap-4 text-sm"><Link href={`/settings/users/${profile.id}/logins`} className="underline">Login history</Link><Link href={`/settings/users/${profile.id}/activity`} className="underline">Activity log</Link></div></div>
        <dl className="mt-8 grid gap-4 border-y border-[#d7ddd5] py-5 sm:grid-cols-2"><dt>Status</dt><dd>{profile.status}</dd><dt>Registered</dt><dd>{new Date(profile.created_at).toLocaleString()}</dd><dt>Last login</dt><dd>{profile.last_login_at ? new Date(profile.last_login_at).toLocaleString() : '-'}</dd><dt>Successful logins</dt><dd>{profile.login_count}</dd><dt>Failed attempts</dt><dd>{profile.failed_login_attempts}</dd><dt>Roles</dt><dd>{roles.join(', ') || '-'}</dd></dl>
        <form onSubmit={(event) => { event.preventDefault(); send('profile', 'PUT', form); }} className="mt-8 grid gap-3 border-t border-[#d7ddd5] pt-5 sm:grid-cols-2"><h2 className="font-semibold sm:col-span-2">Edit profile</h2>{notice.message && <p role="alert" className="sm:col-span-2">{notice.message}</p>}<input required placeholder="First name" value={form.first_name} onChange={(event) => update('first_name', event.target.value)} className="border p-2" /><input required placeholder="Second name" value={form.second_name} onChange={(event) => update('second_name', event.target.value)} className="border p-2" /><input required type="email" placeholder="Email" value={form.email} onChange={(event) => update('email', event.target.value)} className="border p-2 sm:col-span-2" /><input type="password" placeholder="Current password" value={form.current_password} onChange={(event) => update('current_password', event.target.value)} className="border p-2" /><input type="password" placeholder="New password" value={form.password} onChange={(event) => update('password', event.target.value)} className="border p-2" /><input type="password" placeholder="Confirm new password" value={form.password_confirmation} onChange={(event) => update('password_confirmation', event.target.value)} className="border p-2" /><button disabled={processing} className="bg-[#34795c] px-4 py-2 text-white sm:col-span-2">Save profile</button></form>
    </CompanyLayout>;
}