import { Link, useForm, usePage } from '@inertiajs/react';
import { translate } from '../../i18n';

export default function Login({ accountType }) {
    const { errors, registrationOpen, locale } = usePage().props;
    const form = useForm({ email: '', password: '', remember: false });
    const platform = accountType === 'super_admin';
    const t = (key) => translate(locale, key);
    function submit(event) { event.preventDefault(); form.post(platform ? '/super-admin/login' : '/login'); }
    return <div className="login-page"><div className="login-decoration"><div className="login-orbit orbit-one" /><div className="login-orbit orbit-two" /><div className="login-copy"><div className="brand login-brand"><div className="brand-mark">◆</div><div><strong>E‑Zaki</strong><span>ERP / BUSINESS OS</span></div></div><h1>{platform ? t('platformAdmin') : t('companyWorkspace')}<br /><span>{platform ? 'Platform control.' : 'إدارة أعمالك بثقة.'}</span></h1><p>{t(platform ? 'platformSignInCopy' : 'companySignInCopy')}</p><div className="login-proof">✓ <span>{platform ? 'إدارة آمنة للشركات والاشتراكات' : 'مساحة عمل آمنة وموحدة لشركتك'}</span></div></div></div><form className="login-card" onSubmit={submit}><div className="login-card-head"><div className="eyebrow">● {platform ? t('platformSignIn') : t('companySignIn')}</div><h2>{t('signIn')}</h2><p>{t(platform ? 'platformSignInCopy' : 'companySignInCopy')}</p></div><label className="field"><span>{t('email')}</span><div className="field-control"><input autoComplete="username" type="email" value={form.data.email} onChange={(event) => form.setData('email', event.target.value)} /></div></label>{errors.email && <div className="login-error">{errors.email}</div>}<label className="field"><span>{t('password')}</span><div className="field-control"><input autoComplete="current-password" type="password" value={form.data.password} onChange={(event) => form.setData('password', event.target.value)} /></div></label>{errors.password && <div className="login-error">{errors.password}</div>}<div className="login-options"><label><input type="checkbox" checked={form.data.remember} onChange={(event) => form.setData('remember', event.target.checked)} /> {t('rememberMe')}</label><span>{locale === 'ar' ? 'دخول محمي' : 'Secure sign in'}</span></div><button disabled={form.processing} className="primary-button login-button" type="submit">{t('signIn')} ←</button>{!platform && registrationOpen && <small className="login-foot">{t('newCompany')} <Link href="/register">{t('createRequest')}</Link></small>}</form></div>;
}
